#!/bin/sh

########### the initial part will be the same for all assignments
set -e    # halt on first error

link=all  # link all binaries by default
linked=no # track whether we linked

case $1 in  
  -nolink) link=none ; shift ;;  # don't link
  -link)   [ -n "$2" ] || { echo "You need to say *what* to link" >&2; exit 1; }
           link="$2" ; shift ; shift ;;  # link only one binary
esac

# use 'gcc' as the C compiler (at home, you could try 'clang')
CC=gcc

# the next two lines enable you to compile and link against CII40
CIIFLAGS=`pkg-config --cflags cii40`
CIILIBS=`pkg-config --libs cii40`

# the next three lines enable you to compile and link against course software
CFLAGS="-I. -I/comp/40/include $CIIFLAGS"
LIBS="$CIILIBS -larith40 -lnetpbm -lpnm -lpnmrdr -lm"    # might add more libraries for some projects
LFLAGS="-L/comp/40/lib64"

# these flags max out warnings and debug info
FLAGS="-g -O -Wall -Wextra -Werror -Wfatal-errors -std=c99 -pedantic"

rm -f *.o  # make sure no object files are left hanging around

case $# in
  0) set *.c ;; # if no args are given, compile all .c files
esac

# compile each argument to a .o file
for cfile 
do
  $CC $FLAGS $CFLAGS -c $cfile
done

########### the middle part is different for each assignment
# link together .o files + libraries to make executable binaries
# using one case statement per executable binary
case $link in
  all|testmain) $CC $FLAGS $LFLAGS -o testmain testmain.o block_to_rgb.o rgb_to_block.o float_to_compvid.o compvid_to_float.o test_to_bits.o bits_to_test.o test_to_compvid.o compvid_to_test.o bitpack.o a2plain.o uarray2.o $LIBS 
                  linked=yes ;;
esac

case $link in
  all|testbit) $CC $FLAGS $LFLAGS -o testbit testbit.o bitpack.o $LIBS
                  linked=yes ;;
esac

case $link in
  all|ppmdif) $CC $FLAGS $LFLAGS -o ppmdif ppmdif.o a2plain.o uarray2.o $LIBS
                  linked=yes ;;
esac


########### the final part is the same for each assignment
# error if asked to link something we didn't recognize
if [ $linked = no ]; then
  case $link in  # if the -link option makes no sense, complain 
    none) ;; # OK, do nothing
    *) echo "`basename $0`: don't know how to link $link" 1>&2 ; exit 1 ;;
  esac
fi
